### ISSUE TITLE
SHAP (tabular) too large dataset size problem

### ISSUE THREAD

**Issue by eunchongailabo** [sony/nnc-plugin#12]
I tried to use SHAP (tabular) plugin on NNC, but I got an error like below.
```
Traceback (most recent call last):
  File "C:\neural_network_console\libs\plugins\_Post_Process\_XAI\shap_tabular.py", line 92, in <module>
    main()
  File "C:\neural_network_console\libs\plugins\_Post_Process\_XAI\shap_tabular.py", line 88, in main
    args.func(args)
  File "C:\neural_network_console\libs\plugins\_Post_Process\_XAI\shap_tabular.py", line 38, in func
    f'dataset size of {data.shape} might be too large to execute shap computation.')
Exception: dataset size of (27200, 33) might be too large to execute shap computation.
```
I use Windows 11 NNC 2.1.7990 version.

So my question is 
1. Is it bug?
2. If not, How large is the dataset size limit?
2. What should I do?

**Comment by eunchongailabo** [comment]
It seems come from memory limit.

I edited C:\neural_network_console\libs\plugins\_Post_Process\_XAI\shap_tabular_utils\calculate.py, line 23, in check_datasize

from `std: int = 10` to `std: int = 16`

due to my PC has 32GB that I can use 16GB. 

It solved.

**Comment by TomonobuTsujikawa** [comment]
Thank you for your question, and also thank you for solution.

Currently, when this plugin receives large data, it may fail due to lack of memory.
Therefore, it runs only if estimated used memory is less than 10GB.
If more memory is available, it is correct to change `std` value as you did.

We will consider the solution to be better.
